### ISSUE TITLE
a issue with hideBBcode extension

### ISSUE THREAD

**Issue by OmkePom** [AlexSheer/phpbb3.1-Knowledge-Base#8]
Got this masage afther install,

`**[phpBB Debug] PHP Notice: in file [ROOT]/ext/marcovo/hideBBcode/event/listener.php on line 114: Indirect modification of overloaded property phpbb\user::$lang has no effect**`

When i turn off hideBBcode extension, it works afther i set Language for me to nl and create a nl-language map.
I will make a translate to nl, will u fix the ERROR for me? thx

**Comment by AlexSheer** [comment]
The problem has nothing to do with my expansion
